### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by adamzerner** [adamzerner/rfui#36]
See https://chakra-ui.com/docs/components/switch/usage

https://webdesign.tutsplus.com/toggle-switch-component-with-css-checkbox-hack--cms-35011t

https://web.dev/articles/building/a-switch-component

https://uxplanet.org/ui-switch-component-3f29bc7f4f45

**Comment by hapaxlife** [comment]
See You don't need JavaScript for that : https://www.htmhell.dev/adventcalendar/2023/2/ 

to wrap it in atom without javascript

**Comment by adamzerner** [comment]
@hapaxlife Will do. Thanks for the tip.
